import assert from 'node:assert/strict';
import {integrationConfig} from './local-integration.ts';
import {DevelopmentClient} from '../development/client.ts';
import {client} from '../wsl-worker/main.ts';
import {digest} from '../shared/publication.ts';
import {validationCommands} from '../shared/repositories.ts';

const {tokens,base}=await integrationConfig();
const viewer=new DevelopmentClient(base,tokens.viewer),worker=client(base,tokens.worker),workerReader=new DevelopmentClient(base,tokens.worker),other=new DevelopmentClient(base,tokens.other);
assert.equal((await fetch(base+'api/development/publications/00000000-0000-0000-0000-000000000000')).status,401);
const {id:taskId}=await viewer.submit({repoId:'private-agent',baseRef:'epic/development-runner',goal:'Synthetic publication API lifecycle; no model or remote writes.',acceptanceCriteria:['separate audit log'],orchestratorProfileId:'plan-codex-luna',executionProfileId:'edit-codex-luna'},crypto.randomUUID());
await worker('/api/development/runner-heartbeat',{available:true});
const run=await worker('/api/claim',{protocol:'development-v1',taskKind:'development',provider:'codex-luna'}) as any;assert.equal(run.job_id,taskId);
const manifest={version:1,taskId,owner:'local',repoId:'private-agent',baseRef:'epic/development-runner',baseSha:'a'.repeat(40),headSha:'b'.repeat(40),branch:'feature/development-task-'+taskId,contentHash:'c'.repeat(64),validation:'private-agent-v1',checks:validationCommands('private-agent'),mode:'local_only'};
const artifact={...manifest,artifactId:await digest(manifest)};
await worker('/api/development/tasks/'+taskId+'/operation',{token:run.token,name:'artifact',fingerprint:'f'.repeat(64),result:JSON.stringify(artifact)});
await worker('/api/runs/'+run.id+'/complete',{token:run.token,result:JSON.stringify({...artifact,outcome:'local_only',review:'pending'}),error:null});
await worker('/api/development/runner-heartbeat',{available:false});
const before=await viewer.status(taskId),input={taskId,artifactId:artifact.artifactId,repoId:manifest.repoId,baseRef:manifest.baseRef,baseSha:manifest.baseSha,headSha:manifest.headSha,remoteBaseSha:'d'.repeat(40),title:'Synthetic PR',body:'No real external effects.',approved:true},key=crypto.randomUUID();
await assert.rejects(workerReader.approvePublication(input,key),/403/);
const {id}=await viewer.approvePublication(input,key);assert.equal((await viewer.approvePublication(input,key)).id,id);
assert.equal((await workerReader.publication(id)).artifact.headSha,manifest.headSha);
await assert.rejects(other.publication(id),/404/);
await assert.rejects(viewer.request('/api/development/publications/'+id+'/operation',{name:'push'}),/403/);
await assert.rejects(other.request('/api/development/publications/'+id+'/operation',{name:'push'}),/404/);
await assert.rejects(viewer.approvePublication({...input,title:'changed'},key),/409/);
const endpoint='/api/development/publications/'+id+'/operation';
await assert.rejects(worker(endpoint,{name:'push',result:{sha:manifest.headSha}}),/409/);
assert.equal((await worker(endpoint,{name:'push'}) as any).fresh,true);
assert.equal((await worker(endpoint,{name:'push'}) as any).fresh,false);
await worker(endpoint,{name:'push',result:{sha:manifest.headSha}});
assert.equal((await worker(endpoint,{name:'pull-request'}) as any).fresh,true);
await worker(endpoint,{name:'pull-request',result:{url:'https://github.com/FYuki/private-agent/pull/999999'}});
assert.equal((await viewer.publication(id)).state,'published');
const after=await viewer.status(taskId);assert.equal(after.state,before.state);assert.equal(after.result,before.result);assert.deepEqual(after.operations,before.operations);
await assert.rejects(worker('/api/development/tasks/'+taskId+'/operation',{token:run.token,name:'push',fingerprint:'f'.repeat(64)}),/409/);
console.log(JSON.stringify({localSQLite:true,publicationApi:true,unauthenticatedDenied:true,roleOwnerIsolation:true,runUnchanged:true,remoteWrites:false,modelCalls:false}));
