import {mkdtemp,mkdir,writeFile,symlink,unlink} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {execFileSync} from 'node:child_process';
import assert from 'node:assert/strict';
const root=await mkdtemp(join(tmpdir(),'watch-binding-')),config=join(root,'config'),clones=join(root,'clones'),clone=join(clones,'task'),slug='20261005-060000-binding',order='PA:synthetic\nRequirements, AC and Validation\n',taskDir='.takt/tasks/synthetic',branch='takt/1/synthetic';
for(const p of [config,clones,clone,join(root,taskDir),join(root,'.takt/clone-meta'),join(clone,'.takt/runs',slug,'context/task')])await mkdir(p,{recursive:true});
await writeFile(join(config,'config.yaml'),'language: en\nworktree_dir: '+clones+'\n');
await writeFile(join(root,'.takt/clone-meta','takt--1--synthetic.json'),JSON.stringify({branch,clonePath:clone}));
await writeFile(join(root,taskDir,'order.md'),order);const runOrder=join(clone,'.takt/runs',slug,'context/task/order.md');await writeFile(runOrder,order);
const task={name:'synthetic',status:'completed',created_at:'2026-10-05T06:00:00.000Z',started_at:'2026-10-05T06:00:01.000Z',completed_at:'2026-10-05T06:00:02.000Z',summary:'PA:synthetic',task_dir:taskDir,workflow:'default',worktree:true,branch,worktree_path:clone,run_slug:slug};
const save=async(extra={})=>writeFile(join(root,'.takt/tasks.yaml'),JSON.stringify({tasks:[{...task,...extra}]}));await save();
const run=()=>JSON.parse(execFileSync(process.execPath,['development/watch-run-binding.mjs',resolve('runtime/takt'),root,config,clones,'synthetic',slug,'default'],{input:order,encoding:'utf8',stdio:['pipe','pipe','pipe']}));
const bound=run();assert.ok(bound.executionTask.includes('.takt/runs/'+slug+'/context/task/order.md'));assert.notEqual(bound.executionTask,order);assert.equal(bound.clone,clone);
for(const extra of [{run_slug:'another'},{status:'running'},{workflow:'simple'},{summary:'foreign'},{task_dir:'../outside'}]){await save(extra);assert.throws(run);}await save();
await writeFile(runOrder,'tampered');assert.throws(run);await writeFile(runOrder,order);
await writeFile(join(root,taskDir,'order.md'),'changed');assert.throws(run);await writeFile(join(root,taskDir,'order.md'),order);
await unlink(runOrder);await symlink(join(root,taskDir,'order.md'),runOrder);assert.throws(run);
console.log(JSON.stringify({officialRunBinding:true,orderPointer:true,foreignRunAndOrderDenied:true,symlinkDenied:true,modelCalls:0}));
