import assert from 'node:assert/strict';
import {integrationConfig} from './local-integration.ts';
import {DevelopmentClient} from '../development/client.ts';
import {client} from '../wsl-worker/main.ts';
const {tokens,base}=await integrationConfig();
const viewer=new DevelopmentClient(base,tokens.viewer,{allowWatchTest:true}),worker=client(base,tokens.worker),other=new DevelopmentClient(base,tokens.other);
const spec={repoId:'private-agent',baseRef:'epic/development-runner',goal:'Synthetic watch SQLite lifecycle',acceptanceCriteria:['No provider call'],executionProfileId:'takt-watch',watch:{issue:1,validation:['Synthetic host proof']}};
assert.equal((await viewer.profiles()).profiles.executors.find((p:any)=>p.id==='takt-watch').available,false);
assert.throws(()=>new DevelopmentClient(base,tokens.viewer).submit(spec,crypto.randomUUID()),/watch_runtime_validation_pending/);
const first=await viewer.submit(spec,crypto.randomUUID()),dependent=await viewer.submit({...spec,watch:{...spec.watch,dependencies:[first.id]}},crypto.randomUUID());
await assert.rejects(other.status(first.id),/403/);
await worker('/api/development/runner-heartbeat',{available:true,executionProfile:'takt-simple'});
await assert.rejects(worker('/api/claim',{protocol:'development-v1',taskKind:'development',provider:'codex-luna',executionProfile:'takt-watch'}),/409/);
await worker('/api/development/runner-heartbeat',{available:true,executionProfile:'takt-watch'});
const run=await worker('/api/claim',{protocol:'development-v1',taskKind:'development',provider:'codex-luna',executionProfile:'takt-watch'}) as any;
assert.ok(run,'watch lease requires positive Sol capacity');
assert.equal(run.job_id,first.id);await viewer.cancel(first.id);await assert.rejects(worker('/api/runs/'+run.id+'/heartbeat',{token:run.token}),/409/);await worker('/api/runs/'+run.id+'/complete',{token:run.token,result:null,error:'cancelled'});
assert.equal(await worker('/api/claim',{protocol:'development-v1',taskKind:'development',provider:'codex-luna',executionProfile:'takt-watch'}),null);
assert.equal((await viewer.status(dependent.id)).state,'queued');await viewer.cancel(dependent.id);
await worker('/api/development/runner-heartbeat',{available:false,executionProfile:'takt-watch'});
console.log(JSON.stringify({localSQLiteWatch:true,capacityEnabled:!!run,profileFenced:true,dependencyWait:true,cancelFenced:true,providerExecuted:false}));
