export const developmentHtml=`<!doctype html><html lang="ja"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>開発タスク · Private Agent</title><style>
body{font:16px system-ui;background:#f3f5f7;color:#14283a;max-width:720px;margin:auto;padding:24px}label{display:block;margin:18px 0 6px}input,textarea,select,button{font:inherit;padding:12px;border:1px solid #bcc9d2;border-radius:8px;box-sizing:border-box}input,textarea,select{width:100%}button{background:#173e56;color:white;margin:12px 8px 0 0}button:disabled{opacity:.5}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:white;padding:18px}p{line-height:1.6}</style>
<a href="/">定期タスクへ</a><h1>開発タスク</h1><p>計画を作成し、専用作業環境で編集・テストします。管理者が許可したrepoで実行します。通常はローカル成果物と検証結果を保存します。公開が別途許可された場合だけdraft PRを作成します。</p>
<form id="login"><label>閲覧トークン<input id="token" type="password" autocomplete="off" required></label><button>接続</button></form><button id="logout" hidden>ログアウト</button>
<section id="workspace" hidden><form id="task"><label>対象repo<select id="repository"></select></label><p id="target"></p><p id="capacity"></p><label>目標<textarea id="goal" maxlength="4096" required></textarea></label><label>受入条件（1行に1つ）<textarea id="criteria" required></textarea></label><label>司令塔モデル<select id="orchestrator"></select></label><label>実行CLI / モデル<select id="executor"></select></label><button id="submit">タスクを送信</button><button id="new" type="button">新しい送信ID</button></form><label>タスクID<input id="task-id" autocomplete="off"></label><button id="refresh">状態を確認</button><button id="cancel">キャンセル</button><p><a id="pr-link" hidden target="_blank" rel="noopener noreferrer">draft PRを開く</a></p><pre id="result"></pre></section><p id="status" role="status">トークンは画面を閉じると消えます。</p><script src="/development.js"></script></html>`;

export const developmentScript=`
const $=id=>document.getElementById(id);let session={token:'',generation:0,controller:new AbortController()},config,key=crypto.randomUUID();
const current=s=>s===session&&!s.controller.signal.aborted;
function change(token){$('submit').disabled=false;session.controller.abort();session={token,generation:session.generation+1,controller:new AbortController()};config=null;$('capacity').textContent='';key=crypto.randomUUID();$('workspace').hidden=true;$('logout').hidden=!token;$('result').textContent='';$('pr-link').hidden=true;$('pr-link').removeAttribute('href');$('task-id').value='';$('goal').value='';$('criteria').value='';$('repository').replaceChildren();$('orchestrator').replaceChildren();$('executor').replaceChildren();$('status').textContent=token?'接続中…':'ログアウトしました。';}
async function api(path,body,s=session){const r=await fetch(path,{method:body===undefined?'GET':'POST',redirect:'error',signal:s.controller.signal,headers:{Authorization:'Bearer '+s.token,'Content-Type':'application/json','Idempotency-Key':key},...(body===undefined?{}:{body:JSON.stringify(body)})});if(!r.ok)throw Error('操作できません ('+r.status+')');return r.json();}
function fail(e,s){if(current(s))$('status').textContent=e.message;}
$('login').onsubmit=async e=>{e.preventDefault();const token=$('token').value;$('token').value='';change(token);const s=session;try{const c=await api('/api/development/config',undefined,s);if(!current(s))return;config=c;$('capacity').textContent=c.capacity?'設定枠 Sol '+(c.capacity.models['codex-sol']||0)+' / Luna '+c.capacity.models['codex-luna']+' / 共有 '+c.capacity.sharedGroupLimit+'。watchはplan系列のjob 1枠。内部レビューは並列実行。':'';const repos=c.repositories||[{repoId:c.repoId,baseRef:c.baseRef}];for(const p of repos){const o=document.createElement('option');o.value=p.repoId;o.textContent=p.repoId;$('repository').append(o);}$('repository').value=c.repoId;$('target').textContent=c.repoId+' → '+c.baseRef;for(const [id,items,def] of [['orchestrator',c.profiles.orchestrators,c.defaults.orchestratorProfileId],['executor',c.profiles.executors,c.defaults.executionProfileId]]){for(const p of items){const o=document.createElement('option');o.value=p.id;o.textContent=p.id+(p.available?'':' — '+p.reason);o.disabled=!p.available;$(id).append(o);}$(id).value=def;}$('workspace').hidden=false;$('status').textContent='接続しました。';}catch(e){fail(e,s);}};
$('logout').onclick=()=>change('');$('new').onclick=()=>{key=crypto.randomUUID();$('submit').disabled=false;$('task-id').value='';$('result').textContent='';$('pr-link').hidden=true;$('pr-link').removeAttribute('href');$('status').textContent='新しい送信IDを発行しました。';};
$('task').onsubmit=async e=>{e.preventDefault();if(!config)return;const s=session,k=key;$('submit').disabled=true;try{const r=await api('/api/development/tasks',{repoId:config.repoId,baseRef:config.baseRef,goal:$('goal').value,acceptanceCriteria:$('criteria').value.split('\\n').map(x=>x.trim()).filter(Boolean),orchestratorProfileId:$('orchestrator').value,executionProfileId:$('executor').value},s);if(current(s)&&k===key){$('task-id').value=r.id;await refresh(s,k);}}catch(e){if(k===key)fail(e,s);}finally{if(current(s)&&k===key)$('submit').disabled=false;}};
function taskPath(){const id=$('task-id').value.trim();if(!/^[a-f0-9-]{36}$/.test(id))throw Error('タスクIDを確認してください');return '/api/development/tasks/'+id;}
async function refresh(s=session,k=key){try{const id=$('task-id').value.trim(),path=taskPath();const r=await api(path,undefined,s);if(!current(s)||k!==key||$('task-id').value.trim()!==id)return;$('result').textContent=JSON.stringify(r,null,2);$('pr-link').hidden=true;$('pr-link').removeAttribute('href');let outcome;try{outcome=JSON.parse(r.result||'null');}catch{}const repo=r.spec?.repoId||'private-agent';const prefix=['private-agent','local-GPT-live'].includes(repo)?'https://github.com/FYuki/'+repo+'/pull/':'invalid:';if(typeof outcome?.prUrl==='string'&&outcome.prUrl.startsWith(prefix)){const n=outcome.prUrl.slice(prefix.length);if(n.length>0&&n.length<16&&[...n].every(c=>c>='0'&&c<='9')){$('pr-link').href=outcome.prUrl;$('pr-link').hidden=false;}}$('status').textContent=r.queueReason||r.error||r.state;}catch(e){if(k===key)fail(e,s);}}
$('refresh').onclick=()=>refresh();$('cancel').onclick=async()=>{const s=session;try{await api(taskPath()+'/cancel',{},s);if(current(s))await refresh(s);}catch(e){fail(e,s);}};
$('repository').onchange=()=>{if(!config)return;const p=(config.repositories||[{repoId:config.repoId,baseRef:config.baseRef}]).find(p=>p.repoId===$('repository').value);if(!p)return;config={...config,repoId:p.repoId,baseRef:p.baseRef};$('target').textContent=p.repoId+' → '+p.baseRef;$('new').onclick();};
$('executor').onchange=()=>{$('orchestrator').value=$('executor').value==='takt-simple'?'programmatic':'plan-codex-luna';};
`;
